@startuml

title __APP's Class Diagram__\n

  namespace com.example.quiztest1 {
    class com.example.quiztest1.AboutActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.BuildConfig {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.EndlessActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.FAQActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.FriendsActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.Global {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.HelpActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.LeaderboardActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.LevelChoiceActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.LoginActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.N4EnglishActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.N4KanaActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.N5EnglishActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.N5KanaActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.ProfileActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.RegisterActivity {
    }
  }
  

  namespace com.example.quiztest1 {
    class com.example.quiztest1.SettingsActivity {
    }
  }
  

  com.example.quiztest1.AboutActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.EndlessActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.FAQActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.FriendsActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.HelpActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.LeaderboardActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.LevelChoiceActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.LoginActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.N4EnglishActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.N4KanaActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.N5EnglishActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.N5KanaActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.ProfileActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.RegisterActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.quiztest1.SettingsActivity -up-|> androidx.appcompat.app.AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
